<a href="https://colab.research.google.com/github/TaraRasti/Deep_Learning_F20_Assignments/blob/master/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import h5py
import torch

Create a 3 * 3 random tensor as float

In [2]:
x = torch.randn(3, 3)
x

tensor([[-0.4785,  1.2802,  0.5557],
        [-0.1511,  0.7322, -1.1557],
        [ 1.3979, -1.8262,  0.2930]])

In [3]:
x.dtype

torch.float32

Create a 4 * 4 random tensor as double

In [4]:
y = torch.rand(4,4,dtype=torch.double)
y

tensor([[0.9632, 0.3697, 0.6853, 0.9605],
        [0.1363, 0.1349, 0.9431, 0.4719],
        [0.2503, 0.4548, 0.5488, 0.1162],
        [0.3992, 0.6200, 0.3333, 0.3959]], dtype=torch.float64)

Create a 3 * 4 * 5 random tensor as short type

In [5]:
z = torch.randint(0,255,(5, 3, 4), dtype=torch.short)

z

tensor([[[251, 216, 128,  76],
         [138,  37, 184, 180],
         [ 32, 152, 182, 208]],

        [[201,  61, 103, 102],
         [ 42,  26, 231, 238],
         [198, 140, 134, 193]],

        [[222,  48, 107,  53],
         [ 52,  17,  39, 197],
         [190, 165, 121,  67]],

        [[176,  42, 249,   0],
         [200,  59, 101, 132],
         [138, 251,  93, 254]],

        [[ 54, 118,   1, 131],
         [ 54, 199,  71, 150],
         [146, 240,  63, 214]]], dtype=torch.int16)

Change the elements in GPU

In [6]:
x.cuda()


tensor([[-0.4785,  1.2802,  0.5557],
        [-0.1511,  0.7322, -1.1557],
        [ 1.3979, -1.8262,  0.2930]], device='cuda:0')

In [7]:
y.cuda()

tensor([[0.9632, 0.3697, 0.6853, 0.9605],
        [0.1363, 0.1349, 0.9431, 0.4719],
        [0.2503, 0.4548, 0.5488, 0.1162],
        [0.3992, 0.6200, 0.3333, 0.3959]], device='cuda:0',
       dtype=torch.float64)

In [8]:
z.cuda()

tensor([[[251, 216, 128,  76],
         [138,  37, 184, 180],
         [ 32, 152, 182, 208]],

        [[201,  61, 103, 102],
         [ 42,  26, 231, 238],
         [198, 140, 134, 193]],

        [[222,  48, 107,  53],
         [ 52,  17,  39, 197],
         [190, 165, 121,  67]],

        [[176,  42, 249,   0],
         [200,  59, 101, 132],
         [138, 251,  93, 254]],

        [[ 54, 118,   1, 131],
         [ 54, 199,  71, 150],
         [146, 240,  63, 214]]], device='cuda:0', dtype=torch.int16)

Display the order of the elements and its transpose in the memory then use storage offset and contiguous

In [9]:
x.storage()

 -0.4785480201244354
 1.2801979780197144
 0.5556941032409668
 -0.15113374590873718
 0.7322414517402649
 -1.1557188034057617
 1.3979240655899048
 -1.8262081146240234
 0.2929977476596832
[torch.FloatStorage of size 9]

In [10]:
x.storage_offset()

0

In [11]:
x.contiguous()

tensor([[-0.4785,  1.2802,  0.5557],
        [-0.1511,  0.7322, -1.1557],
        [ 1.3979, -1.8262,  0.2930]])

In [12]:
x_t=torch.transpose(x,0,1)
x_t

tensor([[-0.4785, -0.1511,  1.3979],
        [ 1.2802,  0.7322, -1.8262],
        [ 0.5557, -1.1557,  0.2930]])

In [13]:
x_t.storage()

 -0.4785480201244354
 1.2801979780197144
 0.5556941032409668
 -0.15113374590873718
 0.7322414517402649
 -1.1557188034057617
 1.3979240655899048
 -1.8262081146240234
 0.2929977476596832
[torch.FloatStorage of size 9]

In [14]:
x_t.storage_offset()

0

In [15]:
x_t.contiguous()

tensor([[-0.4785, -0.1511,  1.3979],
        [ 1.2802,  0.7322, -1.8262],
        [ 0.5557, -1.1557,  0.2930]])

In [16]:
y.storage()

 0.9631800295598044
 0.36970989325894477
 0.6852532004071467
 0.9605119456473367
 0.1363425401282914
 0.13491056375129729
 0.9430814391016936
 0.47186925848541417
 0.2502757959411678
 0.4548418618572133
 0.5488003508408303
 0.11623108053433417
 0.3991970143690857
 0.6200367233852716
 0.33332135999617707
 0.39589892348178024
[torch.DoubleStorage of size 16]

In [17]:
y.storage_offset()

0

In [18]:
y.contiguous()

tensor([[0.9632, 0.3697, 0.6853, 0.9605],
        [0.1363, 0.1349, 0.9431, 0.4719],
        [0.2503, 0.4548, 0.5488, 0.1162],
        [0.3992, 0.6200, 0.3333, 0.3959]], dtype=torch.float64)

In [19]:
y_t=torch.transpose(y,0,1)
y_t

tensor([[0.9632, 0.1363, 0.2503, 0.3992],
        [0.3697, 0.1349, 0.4548, 0.6200],
        [0.6853, 0.9431, 0.5488, 0.3333],
        [0.9605, 0.4719, 0.1162, 0.3959]], dtype=torch.float64)

In [20]:
y_t.storage()

 0.9631800295598044
 0.36970989325894477
 0.6852532004071467
 0.9605119456473367
 0.1363425401282914
 0.13491056375129729
 0.9430814391016936
 0.47186925848541417
 0.2502757959411678
 0.4548418618572133
 0.5488003508408303
 0.11623108053433417
 0.3991970143690857
 0.6200367233852716
 0.33332135999617707
 0.39589892348178024
[torch.DoubleStorage of size 16]

In [21]:
y_t.storage_offset()

0

In [22]:
y_t.contiguous()

tensor([[0.9632, 0.1363, 0.2503, 0.3992],
        [0.3697, 0.1349, 0.4548, 0.6200],
        [0.6853, 0.9431, 0.5488, 0.3333],
        [0.9605, 0.4719, 0.1162, 0.3959]], dtype=torch.float64)

In [23]:
z.storage()

 251
 216
 128
 76
 138
 37
 184
 180
 32
 152
 182
 208
 201
 61
 103
 102
 42
 26
 231
 238
 198
 140
 134
 193
 222
 48
 107
 53
 52
 17
 39
 197
 190
 165
 121
 67
 176
 42
 249
 0
 200
 59
 101
 132
 138
 251
 93
 254
 54
 118
 1
 131
 54
 199
 71
 150
 146
 240
 63
 214
[torch.ShortStorage of size 60]

In [24]:
z.storage_offset()

0

In [25]:
z.contiguous()

tensor([[[251, 216, 128,  76],
         [138,  37, 184, 180],
         [ 32, 152, 182, 208]],

        [[201,  61, 103, 102],
         [ 42,  26, 231, 238],
         [198, 140, 134, 193]],

        [[222,  48, 107,  53],
         [ 52,  17,  39, 197],
         [190, 165, 121,  67]],

        [[176,  42, 249,   0],
         [200,  59, 101, 132],
         [138, 251,  93, 254]],

        [[ 54, 118,   1, 131],
         [ 54, 199,  71, 150],
         [146, 240,  63, 214]]], dtype=torch.int16)

In [26]:
z_t=torch.transpose(z,0,1)
z_t

tensor([[[251, 216, 128,  76],
         [201,  61, 103, 102],
         [222,  48, 107,  53],
         [176,  42, 249,   0],
         [ 54, 118,   1, 131]],

        [[138,  37, 184, 180],
         [ 42,  26, 231, 238],
         [ 52,  17,  39, 197],
         [200,  59, 101, 132],
         [ 54, 199,  71, 150]],

        [[ 32, 152, 182, 208],
         [198, 140, 134, 193],
         [190, 165, 121,  67],
         [138, 251,  93, 254],
         [146, 240,  63, 214]]], dtype=torch.int16)

In [27]:
z_t.storage()

 251
 216
 128
 76
 138
 37
 184
 180
 32
 152
 182
 208
 201
 61
 103
 102
 42
 26
 231
 238
 198
 140
 134
 193
 222
 48
 107
 53
 52
 17
 39
 197
 190
 165
 121
 67
 176
 42
 249
 0
 200
 59
 101
 132
 138
 251
 93
 254
 54
 118
 1
 131
 54
 199
 71
 150
 146
 240
 63
 214
[torch.ShortStorage of size 60]

In [28]:
z_t.storage_offset()

0

In [29]:
z_t.contiguous()

tensor([[[251, 216, 128,  76],
         [201,  61, 103, 102],
         [222,  48, 107,  53],
         [176,  42, 249,   0],
         [ 54, 118,   1, 131]],

        [[138,  37, 184, 180],
         [ 42,  26, 231, 238],
         [ 52,  17,  39, 197],
         [200,  59, 101, 132],
         [ 54, 199,  71, 150]],

        [[ 32, 152, 182, 208],
         [198, 140, 134, 193],
         [190, 165, 121,  67],
         [138, 251,  93, 254],
         [146, 240,  63, 214]]], dtype=torch.int16)

Save and load one among the elements of tensors using torch

In [38]:
with open('float','wb') as file:
  torch.save(x[0,0],file)
with open('float','rb') as file:
  points=torch.load(file)

In [40]:
with open('double','wb') as file:
  torch.save(y[0,0],file)
with open('double','rb') as file:
  points=torch.load(file)

In [41]:
with open('short_type','wb') as file:
  torch.save(z[0,0,0],file)
with open('short_type','rb') as file:
  points=torch.load(file)

Save and load one among the elements of tensors using the h5py file

In [43]:
with h5py.File('x_0_0.hdf5', 'w') as a:
    a.create_dataset('values', data=x[0,0].cpu().numpy())
with h5py.File('y_0_0.hdf5', 'w') as a:
    a.create_dataset('values', data=y[0,0].cpu().numpy())
with h5py.File('z_0_0_0.hdf5', 'w') as a:
    a.create_dataset('values', data=z[0,0,0].cpu().numpy())
with h5py.File('x_0_0.hdf5', 'r') as b:
    print(torch.from_numpy(np.array(b['values'])))
with h5py.File('y_0_0.hdf5', 'r') as b:
    print(torch.from_numpy(np.array(b['values'])))
with h5py.File('z_0_0_0.hdf5', 'r') as b:
    print(torch.from_numpy(np.array(b['values'])))

tensor(-0.4785)
tensor(0.9632, dtype=torch.float64)
tensor(251, dtype=torch.int16)


Show the different true and false requires_grad values in Autograd by the backward method

In [52]:
t1=torch.zeros(10,10)
t2=torch.ones(10,10)
t3=t1+t2
t3.requires_grad

False

In [53]:
t4=torch.randn((10,10),requires_grad=True)
t5=t3+t4
t5.requires_grad

True

In [59]:
from torch.autograd import Variable
x=Variable(2*torch.ones(2,2),requires_grad=True)
x.backward(x)
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])
